// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	wallet "mini-wallet/internal/domain/wallet"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddTransaction provides a mock function with given fields: ctx, t
func (_m *Service) AddTransaction(ctx context.Context, t wallet.Transaction) (wallet.Transaction, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for AddTransaction")
	}

	var r0 wallet.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, wallet.Transaction) (wallet.Transaction, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, wallet.Transaction) wallet.Transaction); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Get(0).(wallet.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, wallet.Transaction) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
